<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="inertia.xacro" />

    <link name="camera_link">
        <visual>
            <geometry>
                <box size="0.1 ${base_width / 3} ${base_height / 3}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="orange" />
        </visual>
        <collision>
            <geometry>
                <box size="0.1 ${base_width / 3} ${base_height / 3}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
        </collision>
        <xacro:box_inertia m="0.1" w="${base_width / 3}" h="${base_height / 3}" d="0.1"
            o_xyz="0 0 0" o_rpy="0 0 0" />
    </link>

    <joint name="base_camera_joint" type="fixed">
        <parent link="base_link" />
        <child link="camera_link" />
        <origin xyz="${base_length / 2} 0 ${base_height / 2}" rpy="0 0 0" />
    </joint>

    <link name="camera_depth_frame" />

    <joint name="camera_depth_joint" type="fixed">
        <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}" />
        <parent link="camera_link" />
        <child link="camera_depth_frame" />
    </joint>

    <!-- <gazebo reference="camera_depth_frame">
        <sensor name="depth_camera" type="depth">
            <gz_frame_id>camera_depth_frame</gz_frame_id>
            <visualize>true</visualize>
            <update_rate>30.0</update_rate>
            <topic>/depth_camera</topic>
            <camera name="camera">
                <horizontal_fov>1.047198</horizontal_fov>
                <image>
                    <width>640</width>
                    <height>480</height>
                    <format>R8G8B8</format>
                </image>
                <clip>
                    <near>0.05</near>
                    <far>3</far>
                </clip>
            </camera>
        </sensor>
    </gazebo> -->
</robot>