<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="base_length" value="0.345" />
    <xacro:property name="base_width" value="0.24" />
    <xacro:property name="base_height" value="0.2" />
    <xacro:property name="wheel_radius" value="0.0325" />
    <xacro:property name="wheel_length" value="0.027" />
    <xacro:property name="sphere_front_radius" value="${wheel_radius/2}" />

    <xacro:include filename="inertia.xacro" />

    <link name="base_footprint" />

    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz="0 0 ${base_height/2}" rpy="0 0 0" />
            <material name="red" />
        </visual>
        <collision>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz="0 0 ${base_height/2}" rpy="0 0 0" />
        </collision>
        <xacro:box_inertia m="5" x="${base_length}" y="${base_width}" z="${base_height}"
            o_xyz="0 0 ${base_height/2}" o_rpy="0 0 0" />
    </link>

    <link name="left_wheel_link">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}" />
            </geometry>
            <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
            <material name="grey" />
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}" />
            </geometry>
            <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
        </collision>
        <xacro:cylinder_inertia m="0.010" radius="${wheel_radius}"
            length="${wheel_length}" o_xyz="0 0 0" o_rpy="${pi / 2.0} 0 0" />
    </link>

    <link name="right_wheel_link">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}" />
            </geometry>
            <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
            <material name="grey" />
            <xacro:cylinder_inertia m="1" radius="${wheel_radius}"
                length="${wheel_length}" o_xyz="0 0 0" o_rpy="${pi / 2.0} 0 0" />
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}" />
            </geometry>
            <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
        </collision>
        <xacro:cylinder_inertia m="0.010" radius="${wheel_radius}"
            length="${wheel_length}" o_xyz="0 0 0" o_rpy="${pi / 2.0} 0 0" />
    </link>

    <link name="caster_wheel_link">
        <visual>
            <geometry>
                <sphere radius="${sphere_front_radius}" />
            </geometry>
            <material name="grey" />
            <origin xyz="0 0 0" rpy="0 0 0" />
        </visual>
        <collision>
            <geometry>
                <sphere radius="${sphere_front_radius}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
        </collision>
        <xacro:sphere_inertia m="0.010" r="${sphere_front_radius}" o_xyz="0 0 0" o_rpy="0 0 0" />
    </link>

    <joint name="base_footprint_base_joint" type="fixed">
        <parent link="base_footprint" />
        <child link="base_link" />
        <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0" />
    </joint>

    <joint name="base_caster_wheel_joint" type="fixed">
        <parent link="base_link" />
        <child link="caster_wheel_link" />
        <origin xyz="${base_width/2} 0 -${sphere_front_radius}" rpy="0 0 0" />
    </joint>

    <joint name="base_left_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="left_wheel_link" />
        <origin xyz="-${base_length/3} ${base_width/2 + wheel_length/2} 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="base_right_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="right_wheel_link" />
        <origin xyz="-${base_length/3} -${base_width/2 + wheel_length/2} 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <gazebo reference="caster_wheel_link">
        <mu1 value="0.001"/>
        <mu2 value="0.001"/>
    </gazebo>

</robot>